/**
 * @fileoverview gRPC-Web generated client stub for backend
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: user_service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as user_service_pb from './user_service_pb'; // proto import: "user_service.proto"


export class UserServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorRegisterContributor = new grpcWeb.MethodDescriptor(
    '/backend.UserService/RegisterContributor',
    grpcWeb.MethodType.UNARY,
    user_service_pb.RegisterContributorRequest,
    user_service_pb.RegisterContributorResponse,
    (request: user_service_pb.RegisterContributorRequest) => {
      return request.serializeBinary();
    },
    user_service_pb.RegisterContributorResponse.deserializeBinary
  );

  registerContributor(
    request: user_service_pb.RegisterContributorRequest,
    metadata?: grpcWeb.Metadata | null): Promise<user_service_pb.RegisterContributorResponse>;

  registerContributor(
    request: user_service_pb.RegisterContributorRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: user_service_pb.RegisterContributorResponse) => void): grpcWeb.ClientReadableStream<user_service_pb.RegisterContributorResponse>;

  registerContributor(
    request: user_service_pb.RegisterContributorRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: user_service_pb.RegisterContributorResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/backend.UserService/RegisterContributor',
        request,
        metadata || {},
        this.methodDescriptorRegisterContributor,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/backend.UserService/RegisterContributor',
    request,
    metadata || {},
    this.methodDescriptorRegisterContributor);
  }

  methodDescriptorGetContributor = new grpcWeb.MethodDescriptor(
    '/backend.UserService/GetContributor',
    grpcWeb.MethodType.UNARY,
    user_service_pb.GetContributorRequest,
    user_service_pb.GetContributorResponse,
    (request: user_service_pb.GetContributorRequest) => {
      return request.serializeBinary();
    },
    user_service_pb.GetContributorResponse.deserializeBinary
  );

  getContributor(
    request: user_service_pb.GetContributorRequest,
    metadata?: grpcWeb.Metadata | null): Promise<user_service_pb.GetContributorResponse>;

  getContributor(
    request: user_service_pb.GetContributorRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: user_service_pb.GetContributorResponse) => void): grpcWeb.ClientReadableStream<user_service_pb.GetContributorResponse>;

  getContributor(
    request: user_service_pb.GetContributorRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: user_service_pb.GetContributorResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/backend.UserService/GetContributor',
        request,
        metadata || {},
        this.methodDescriptorGetContributor,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/backend.UserService/GetContributor',
    request,
    metadata || {},
    this.methodDescriptorGetContributor);
  }

}

